version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  test:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: dotnet test
  build:
    executor: 
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: dotnet build 
