version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  test_the_code:
    executor: 
      name: win/default
    steps:
      - checkout
      - run: dotnet test
  build_the_code:
    executor:
      name: win/default
    steps:
      - checkout 
      - run: dotnet build

workflows:
  test_and_build:
    jobs:
      - test_the_code
      - build_the_code:
          requires:
            - test_the_code